version: "3.5"

networks:
  web:
    external: true
    name: web
  mail:
    external: true
    name: mail
  internal:

services:
  web:
    build:
      context: .
    environment:
      - RELAY_HOST=mail.external.onecall
      - SERVER_NAME=pd.apps.internal.onecall
      - XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST}
      - PHP_IDE_CONFIG=pd
      - PD_SYSTEM=local
    extra_hosts:
      - "local.pd.co.uk:127.0.0.1"
    volumes:
      - .:/var/www/
    labels:
      traefik.backend: web
      traefik.docker.network: web
      traefik.enable: "true"
      traefik.foebis.frontend.rule: Host:local.pd.co.uk
      traefik.foebis.port: 80
      traefik.foebis.protocol: http
    restart: unless-stopped
    networks:
      - web
      - internal
      - mail